name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: 6.x

        # Run tests
        - name: Test
          run: dotnet test

        - name: actions/deploy-pages@v1
          with:
            emit_telemetry: false
            timeout: 600000
            error_count: 10
            reporting_interval: 5000
            artifact_name: github-pages
            preview: false
            
        # Generate the website
        - name: Publish
          run: dotnet publish ./Blazor_Board/Blazor_Board.csproj --configuration Release

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on master
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: Blazor_Board/bin/Release/net6.0/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
            # TODO uncomment the following line if you have a custom domain name
            # cname: demo.meziantou.net
